### ISSUE TITLE
Required space seems to be too large on `zopen upgrade`

### ISSUE THREAD

**Issue by AnthonyGiorgio** [ZOSOpenTools/meta#499] opened 2023-10-13 14:28 UTC
When issuing `zopen upgrade curl`, I noticed that the message showing the newly required disk space seems to be too large.  I find it hard to believe that upgrading curl would require 14MB of additional disk space over the prior version.  Perhaps the code isn't subtracting the existing disk space?

```sh
angio ~> zopen upgrade curl
- Querying remote repo for latest package information
Installing package: curl
- Replacing curl version '8.1.2.20230912_215945' with '8.4.0.20231011_155722'
- Downloading curl-8.4.0.20231011_155722.zos.pax.Z file from remote to zopen package cache...
- Downloaded curl-8.4.0.20231011_155722.zos.pax.Z file from remote to zopen package cache.
- Processing curl-8.4.0.20231011_155722.zos.pax.Z...
After this operation, 14.53 MB of additional disk space will be used.
```

**Comment by MikeFultonDev** [comment] 2023-10-13 22:51
I expect you need both installed for a brief time before deleting the old one sont you? So you would want to include the space of the current one too? But - that’s not my code. @DevonianTeuchter ?

**Comment by AnthonyGiorgio** [comment] 2023-10-13 23:06
The calculation should be `(space of new - space of current)`, and the sign of the result will decide on the adjective in the message (used vs. saved)

**Comment by MikeFultonDev** [comment] 2023-10-14 01:25
So total usage to do install is not something we should communicate (to ensure file system doesn’t croak?)

**Comment by AnthonyGiorgio** [comment] 2023-10-14 11:17
I don't think we can communicate that value properly, as by the time we're going to measure it, the new pax has already been expanded, and it's using disk space somewhere.  All that we can provide at this point is how much more/less space will be consumed after the install completes.

**Comment by IgorTodorovskiIBM** [comment] 2023-10-16 02:21
I believe the upgrade process is a bit different than other packages managers in that it installs a new version of the tool and doesn't replace the current version. @DevonianTeuchter Is this correct? Do we have an option to automatically remove old releases?

We also probably need to consider size of the pax file as since we are downloading it to the file system. Both the expanded size and pax file size are in the metadata:
https://github.com/ZOSOpenTools/meta/blob/main/docs/api/zopen_releases.json#L13-L14

**Comment by AnthonyGiorgio** [comment] 2023-10-16 12:23
Then perhaps we should think about this more.  Upgrading `curl` with a new version is fine, but I see that the existing insecure version is still left in place.  Perhaps we should remove old versions by default?

**Comment by IgorTodorovskiIBM** [comment] 2023-10-16 13:04
Perhaps a prompt (or option) that asks the user if they want to keep older versions? 

> Then perhaps we should think about this more. Upgrading `curl` with a new version is fine, but I see that the existing insecure version is still left in place. Perhaps we should remove old versions by default?

And perhaps we can add some smarts so that it doesn't remove personal builds via zopen build or some way to toggle it.

**Comment by lbdyck** [comment] 2023-10-16 13:08
or a parameter such as `-kill` :)

**Comment by DevonianTeuchter** [comment] 2023-10-18 15:06
Currently, the upgrade process for a package will:
- query the cache for details about the release
- if an update is available, then it will download the pax.Z to the local cache
- reports the new size.  
- unpaxes and moves to the install location
- switches around symlinks
It does not remove the previous version by default - that was the initial design of the package manager, to allow for [up/down]grading at will without a full reinstall, just using zopen-alt to switch symlinks - so that space will still be used. There would also be space taken up by the pax in the cache [if we're getting into that level of detail!].  The zopen clean command is there to remove older versions and reclaim space.  
We could add a parameter on the upgrade (defaulting to [keep-old/remove-old]?) and a global configurable property [ in the etc/zopen heirarchy with other global properties so easily tweakable]. When upgrading with the "remove-old" parameter set, we can use make sure to use the correct terminology/adjectives.
Personal builds will not appear in the release-metadata so we can validate whether something is in that metadata before we uninstall [and possibly ask before we upgrade as a side-project since we will always upgrade!]

**Comment by MikeFultonDev** [comment] 2023-10-18 22:09
i personally like zopen clean being separate. One tool for one task Unix model.

**Comment by MikeFultonDev** [comment] 2023-10-18 23:22
So - currently this is 'working as designed', so closing this. @AnthonyGiorgio if you want some sort of 'install and clean' then please open a separate issue, in which case ideally we would want to indicate MAXIMUM disk usage and AFTER INSTALL disk usage.

**Closed by MikeFultonDev** 2023-10-18 23:22 UTC
